source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '~> 7.1.3'
gem 'sqlite3'
gem 'puma'
gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :test do
  gem 'shoulda-matchers'
  gem 'database_cleaner-active_record'
end 